# Week 10 Seminar notebook: Multilayer neural networks


Problem 1: Given the weights and the input vector below, write the code to calculate the predicted output value y_hat, assuming the model described in the week 9 lecture.

In [ ]:
y

In [19]:
import numpy as np
weights_0_1=np.array([[-.59,.75,-.95],[.34,-.17,.12],[-.72,-.6,.6]])
weights_1_2=np.array([[.93],[-.37],[.38]])
layer_0 = np.array([[ 0, 1, 1 ]])

# Essentially repeats the step
# Due to the syntax in python, you have to transpose first
# q_layer_1 =  weights_0_1.dot(layer_0.T)
q_layer_1_comparison = layer_0.dot(weights_0_1)
print(q_layer_1_comparison)

"""
# For q_layer_1
#  [[-0.2 ]
#  [-0.05]
#  [ 0.  ]]
# For q_layer_1_comparison
# [[-0.2  -0.05  0.  ]]
# As seen in comparison above, the direction of vectors are different
"""

# print(q_layer_1)
q_layer_1 = np.maximum(q_layer_1_comparison,[0,0,0])
print(q_layer_1)
z_1 = q_layer_1.dot(weights_1_2)
print(z_1)
# # q_layer_2 = weights_1_2.dot(q_layer_1.T)

# Relu layer
# layer_1 = np.maximum(q_layer_1,0)




[[-0.38 -0.77  0.72]]
[[0.   0.   0.72]]
[[0.2736]]


Problem 2: Given the true label y=1, and the learning rate as specified below, write the code to perform the backwards pass and update the weights. You should obtain the same weights at t2 as on the week 9 slides.

In [23]:
true_label = np.array([[1]])
learning_rate=0.2

layer_2_del = z_1 - true_label
print(layer_2_del)
layer_1_delta=np.zeros((3,3))


# Basically in backpropagation
# layer_1_delta[0,0]= layer_2_del * weights_1_2[0,0] * (q_layer_1[0,0]>0)
# print(layer_1_delta)
# layer_1_delta[0,1]= layer_2_del * weights_1_2[0,1] * (q_layer_1[0,1]>0)
# layer_1_delta[0,2]= layer_2_del * weights_1_2[0,2] * (q_layer_1[0,2]>0)

# layer_1_delta[1,0]= layer_2_del * weights_1_2[0,0] * (q_layer_1[1,0]>0)
# layer_1_delta[1,1]= layer_2_del * weights_1_2[] * (q_layer_1[1,1]>0)
# layer_1_delta[1,2]= layer_2_del * weights_1_2[1,0] * (q_layer_1[1,2]>0)

# layer_1_delta[2,0]= layer_2_del * weights_1_2[2,0] * (q_layer_1[2,0]>0)
# layer_1_delta[2,1]= layer_2_del * weights_1_2[2,0] * (q_layer_1[2,1]>0)
# layer_1_delta[2,2]= layer_2_del * weights_1_2[2,0] * (q_layer_1[2,2]>0)
# print(layer_1_delta)
# # weights_0_1[0,0] -= layer_1_delta[0,0] * learning_rate
# # weights_0_1[0,1] -= layer_1_delta[0,1] * learning_rate
# # weights_0_1[0,2] -= layer_1_delta[0,2] * learning_rate
# # weights_0_1[1,0] -= layer_1_delta[1,0] * learning_rate
# # weights_0_1[1,1] -= layer_1_delta[1,1] * learning_rate
# # weights_0_1[1,2] -= layer_1_delta[1,2] * learning_rate
# # weights_0_1[2,0] -= layer_1_delta[2,0] * learning_rate
# # weights_0_1[2,1] -=map
# # weights_0_1[2,2] -=

# # weights_1_2[0] -=
# # weights_1_2[1] -=
# # weights_1_2[2] -=

# # print(weight_0_1)
# # print(weight_1_2)

[[-0.7264]]
[[-0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


/tmp/ipython-input-2649343825.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  layer_1_delta[0,0]= layer_2_del * weights_1_2[0,0] * (q_layer_1[0,0]>0)
/tmp/ipython-input-2649343825.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  layer_1_delta[0,1]= layer_2_del * weights_1_2[0,0] * (q_layer_1[0,1]>0)
/tmp/ipython-input-2649343825.py:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  layer_1_delta[0,2]= layer_2_del * weights_1_2[0,0] * (q_layer_1[0,2]>0)


IndexError: index 1 is out of bounds for axis 0 with size 1

Problem 3. Given the training data below, complete the code to train the network to solve the problem. You can use the code in the block below the training block to test that the models predictions from the training inputs are approximately correct.

In [ ]:
inputs = np.array( [[ 0, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 1, 0, 1 ],
                          [ 1, 1, 1 ] ] )

true_labels = np.array([ [0], [1], [1], [0]])

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

learning_rate = 0.35
num_features=3
hidden_size = 3
np.random.seed(1)
weights_0_1 = np.random.rand(num_features,hidden_size)
np.random.seed(1)
weights_1_2 = np.random.rand(hidden_size,1)

loss = []
n_iters=1000
for iteration in range(n_iters):
   layer_2_error = 0
   for i in range(len(inputs)):
      layer_0 = inputs[i]
      #print("L0:")
      #print(layer_0)
      ## Add forward pass
      layer_1 =
      layer_2 =

      layer_2_error+=np.sum((layer_2-true_labels[i])**2)

      ## Add backward pass and update weights

      layer_2_delta =

      layer_1_delta=np.zeros((3,3))
      layer_1_delta[0,0]=
      layer_1_delta[0,1]=
      layer_1_delta[0,2]=

      layer_1_delta[1,0]=
      layer_1_delta[1,1]=
      layer_1_delta[1,2]=

      layer_1_delta[2,0]=
      layer_1_delta[2,1]=
      layer_1_delta[2,2]=

      weights_0_1[0,0] -=
      weights_0_1[0,1] -=
      weights_0_1[0,2] -=
      weights_0_1[1,0] -=
      weights_0_1[1,1] -=
      weights_0_1[1,2] -=
      weights_0_1[2,0] -=
      weights_0_1[2,1] -=
      weights_0_1[2,2] -=

      weights_1_2[0] -=
      weights_1_2[1] -=
      weights_1_2[2] -=


   loss.append(layer_2_error)
plt.plot(range(1,n_iters),loss[1:])
plt.xlabel("number of epochs")
plt.ylabel("loss")

You can view the results as follows

In [ ]:
np. set_printoptions(suppress=True)
for k in range(4):
  layer_0 = inputs[k]
  layer_1 = np.maximum(np.dot(layer_0,weights_0_1),0)
  layer_2 = np.dot(layer_1,weights_1_2)
  print(layer_2)

Problem 4: Once you have a model that makes good predictions, try lowering the learning rate. What do you notice? Why do you think this happens?

Problem 5. Examine the weights in your model. Give a verbal explanation of why they give the correct answer to the XOR problem

Problem 6 (hard problem to try if you have time): rewrite the code you wrote above so that it calculates deltas and updates weights using vector and/or matrix operations rather than element by element